### ISSUE TITLE
Question about target

### ISSUE THREAD

**Issue by ibaryshnikov** [schell/mogwai#15]
Nice work done here! I have a question, is there a reason that `--target no-modules` is used in examples? Since es6 modules support somewhere as good as webassembly support amongst all browsers, it is fine to use `--target web`.
Instead of
```html
<script src="pkg/mogwai_todo.js"></script>
<script type="module">
    window
        .wasm_bindgen('pkg/mogwai_todo_bg.wasm')
         .then( m => m.main() )
         .catch(console.error);
</script>
```
there will be
```html
<script type="module">
import { init } from './pkg/mogwai_todo.js';
window.addEventListener('load', async () => {
    await init();
});
</script>
```

**Comment by schell** [comment]
There's no hard constraint to use `--target no-modules`. This is just the way I set up the template. You're free to do what you like :) Thanks for the inquiry!

**Comment by schell** [comment]
Though it seems compiling with `--target web` and changing the `index.html` is not enough. I get this error in my console: 
```
SyntaxError: import not found: init
```
It looks like `wasm-pack` is not properly exporting `init`?

It works if I add `export` to the `init` function itself in the built JavaScript file (in this case `./pkg/mogwai_todo.js`) and then change the `index.html` page to include both `init` and `main`:
```html
        <script type="module">
         import { init, main } from './pkg/mogwai_todo.js';
         window.addEventListener('load', async () => {
             await init();
             await main();
         });
        </script>
```

**Comment by ibaryshnikov** [comment]
oops, my bad, `init` should be outside of brackets: `import init, { main } from ...`
one more trick, if you change
```rust
#[wasm_bindgen]
pub fn main() -> Result<(), JsValue> {
```
to
```rust
#[wasm_bindgen(start)]
pub fn main() -> Result<(), JsValue> {
```
there will be no need to call `main()`, only `await init()`

**Comment by schell** [comment]
Great! Thank you! Very much appreciated.
