### ISSUE TITLE
suggestion: GizmoBuilder::conditional_boolean_attribute

### ISSUE THREAD

**Issue by binomial0** [schell/mogwai#19]
GizmoBuilder::boolean_attribute sets the attribute to "true" unconditionally.
In my current project, I often want to set a boolean attribute to a value that is not hardcoded, but also not changed based on events. It's dynamically computed when creating the builder. It would be much easier if there was a method `conditional_boolean_attribute` that took a boolean parameter and only set the attribute if this parameter was true.  
Currently, I'm doing something like:
```rust
let builder = create_my_fancy_builder();
let builder = if condition { builder.boolean_attribute("my_attr") } else { builder };
builder
```
It would be great if I could replace this with
```rust
create_my_fancy_builder().conditional_boolean_attribute("my_attr", condition)
```
I think the second variant would be both easier to write and to read.

**Comment by schell** [comment]
Hi! Thanks for your interest and your suggestion, I think it's a good idea. I'll get on it.

**Comment by schell** [comment]
@binomial0 - FYI - in mogwai `0.2.0` the builder pattern will be part of `Gizmo` itself and `GizmoBuilder` is going away. For the next `0.1` release I'll add `GizmoBuilder::conditional_boolean_attribute` but in `0.2` I'll change the signature of `boolean_attribute` to take the conditional.

**Comment by schell** [comment]
Complete! https://docs.rs/mogwai/0.1.6/mogwai/builder/struct.GizmoBuilder.html#method.conditional_boolean_attribute
