### ISSUE TITLE
Add mogwai benchmark to the JS framework benchmark

### ISSUE THREAD

**Issue by Pauan** [schell/mogwai#22]
The [JS framework benchmark](https://github.com/krausest/js-framework-benchmark) is the gold standard for DOM frameworks, it already has several dozen frameworks (including many Rust frameworks). So it would be great to see how mogwai compares.

**Comment by schell** [comment]
That's a great idea. I'll dig in when I can.

**Comment by matthewharwood** [comment]
Could you add SolidJS to the benchmarks I guess it's the gold standard in perf right now

**Comment by schell** [comment]
@matthewharwood - so far it looks like solid is doing something funky in terms of event listening. I'm still digging into its todomvc implementation but if one cannot add todos by firing events from javascript then it simply may not be possible. We'll see.

**Comment by matthewharwood** [comment]
The author of solid is extremely active on GitHub issues.  Maybe ping him and I'm sure he'll offer his help!

**Comment by FranzSkuffka** [comment]
I'm also curious about how solidJS fares against mogwai.

**Comment by schell** [comment]
This is done(ish). https://github.com/krausest/js-framework-benchmark/pull/1171
