### ISSUE TITLE
Where do I start Section produces error

### ISSUE THREAD

**Issue by matthewharwood** [schell/mogwai#28]
Rust noob here so excuse me if I made a dumb mistake:

[Where Do I start doc](https://github.com/schell/mogwai#ok---where-do-i-start)

Producing this error when running build step:

```
C:\Users\matth\@dev\mogwai\demo>wasm-pack build --target no-modules
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
   Compiling demo v0.0.0 (C:\Users\matth\@dev\mogwai\demo)
error[E0599]: no method named `build` found for type `mogwai::gizmo::Gizmo<mogwai::prelude::HtmlElement>` in the current scope
  --> src\lib.rs:29:6
   |
29 |     .build()?
```

**Comment by schell** [comment]
You're right! I just reproduced this myself. I need to update the `mogwai-template` repo. For now you can simply delete that line and it *should* work.

**Comment by schell** [comment]
I've updated that repo: https://github.com/schell/mogwai-template/commit/500f37a42731b5672e98423ac54d30e48abcb83f

**Comment by matthewharwood** [comment]
Fixed but on to the next one: https://github.com/schell/mogwai/pull/29 ;)
