### ISSUE TITLE
Mogwai with updates from global state changes

### ISSUE THREAD

**Issue by alilee** [schell/mogwai#38]
I suspect that managing state independently of interface is a key problem. I think this is the problem Redux is architected to solve. I come down this path from Fulcro (https://github.com/fulcrologic/fulcro; Clojure) which very elegantly decouples components from state by having each do a query against a normalised database.

Is there any appetite to create the layer on top of Mogwai which enables updates to a global state, which then propagate to one or more components? 

```rust
static STATE: Mutex<HashMap<PersonID, (Rc<Person>, Transmitter<PersonChange>)> = Mutex::new(HashMap::new());
```

**Comment by alilee** [comment]
See also this compelling Rust SPA overview which defines the concept as `AppState` but bails out on the solution by hoisting since they are using Yew.

  [http://www.sheshbabu.com/posts/rust-wasm-yew-single-page-application/](http://www.sheshbabu.com/posts/rust-wasm-yew-single-page-application/)

**Comment by alilee** [comment]
And, maybe this is my answer - still interested in your thoughts about the benefits of leveraging `txrx`.

[https://crates.io/crates/reactive-state](https://crates.io/crates/reactive-state)

**Comment by schell** [comment]
That's an interesting proposition, I haven't thought about that before. 

There's nothing keeping you from using `txrx::Transmitter`, `txrx::Receiver` and `DomWrapper` for the view, while maintaining state separately in a structure of your choice, with the access patterns of your choice. The idea would be that you write a function like [`Component::view`](https://github.com/schell/mogwai/blob/38adc80724ea7e4ff63c8084bc14cd2698e36085/mogwai/src/component.rs#L159-L168):

```rust
pub fn my_view(
    tx: Transmitter<SomeModelMsg>,
    rx: Receiver<SomeViewMsg>,
) -> DomWrapper<HtmlElement> {
    dom! {
        <div> ...your markup here - using tx and rx </div>
    }
}
``` 

Then create a pair of txrx, wire them together using a fold function that folds over your custom state structure, or access your db - then pass that `tx` and `rx` into `my_view` to create the view. Once you have that view you can run it. The view (`DomWrapper`) will own everything and when it is `run`, the browser window will own the view.

**Comment by schell** [comment]
BTW, thanks for the links - I'll read them ASAP.

**Comment by alilee** [comment]
[valerie](https://crates.io/crates/valerie) seems to be headed this direction, but I don't see the txrx elegance.

**Comment by schell** [comment]
Ah yes, `valerie` seems very close to `mogwai`, but without an equivalent `txrx` module it lacks any separation between messaging and the view.

**Comment by alilee** [comment]
So they have messaging: using [futures-intrusive](https://crates.io/crates/futures-intrusive). It is hard to use but also bigger. They are using it selectively to link state changes to DOM.

**Comment by schell** [comment]
Ah, ok - I'll have to look into that lib as well.

**Comment by alilee** [comment]
So I've spent the last few days sketching a static (scoped), reactive store in valerie. I think mogwai and txrx would be a good foundation too. If you want to look, I ported react's tictactoe tutorial: [sketch](https://github.com/alilee/valerie/tree/sketch/examples/tictactoe/src).

I think this is the start of a mogwai, redux, svelte in rust thing, which could be very powerful. My rust isn't as good as yours, but hopefully you can see the promise.

**Comment by schell** [comment]
Very cool!

**Comment by alilee** [comment]
I feel I am hitting some limits with valerie (although they are probably just my limits). I am trying to port the tictactoe example over to mogwai as a compare-and-contrast exercise.

**Comment by schell** [comment]
Thank you for your interest! Please let me know where I can help.

**Comment by alilee** [comment]
@schell Hiya - did you see my pull request? - has a question to help me unstick.. thanks.

**Comment by schell** [comment]
Is there more we should discuss here or can I close this ticket @alilee ?

**Comment by schell** [comment]
:bow:
