### ISSUE TITLE
Does mogwai support code-splitting?

### ISSUE THREAD

**Issue by d4h0** [schell/mogwai#41]
Hi,

A few days ago I [posted](https://github.com/schell/mogwai/issues/30#issuecomment-686813903) the question above in a different issue, but I guess the notification was lost somehow, so I post it again as its own issue (which anyway makes more sense).

In the above-linked comment I wrote the following:

> I'm thinking about creating a Rust/WASM-based static website generator similar to Gastby.js (which basically is a combination of a static website generator and a client-side JavaScript application framework).

> One requirement for this is code-splitting (if a website has, say, 10.000 pages, it wouldn't be very performant if all 10k pages are loaded on the first visit... ;)).

> (The great thing with such an approach is that you can include small (or big) apps and dynamic widgets, but otherwise you still have a static website, with all its benefits).

At this point, I  have decided to build the static website generator now, so I'm currently in the phase where I evaluation the technology that I will use – and mogwai looks like a very interesting crate so far.

**Comment by schell** [comment]
Hopefully I answered your question in #30 but I'll keep this here to go more in-depth into the topic.

**Comment by d4h0** [comment]
Thanks, @schell!

In your answer you write the following:

> Code splitting is yet another feature I don't know much about, hehe! I'll have to read up on it. My naive idea is that if you have code that needs to be executed on the server and in the browser then it should live in a library and be wrapped by an excutable that knows where it is to be executed.

I think we are not talking about the same code-splitting :)

I'm talking about this one:

https://reactjs.org/docs/code-splitting.html

Specifically, about [Route-based code-splitting](https://reactjs.org/docs/code-splitting.html#route-based-code-splitting).

Let's say we have a website with 10.000 pages (for example, an online store) and the resulting binary size is 10 MB (which probably could be bigger, I'm not sure). Without code-splitting, these 10 MB would have to be loaded on the first request of a visitor (if my current understanding is correct). With route-based code-splitting, only what is required for a specific page would be loaded (let's say 0.4 MB).

Therefore, I think code-splitting would be a big advantage for content-heavy sites (as described above), or for big single-page applications that use many or big Rust crates.

From my research, it seems, that mostly the code bundler (possibly my static-site generator) would have to implement code-splitting, but I assume in the case of WASM/mogwai applications code-splitting also would need some kind of support on lower levels of the tech stack.

**Comment by schell** [comment]
Ah, I see. That's a tougher problem. I think the most natural way to build a 10,000 page site with rust would be to create one binary that can generate each page, but then yes; the binary size would be the biggest needed to create any page.

**Comment by d4h0** [comment]
Yes, I thought about this, and for simple sites that probably would work. Problems would arise, however, if there are many pages that have unique big dependencies (that are only needed for one or a few pages).

So you say, this is not possible at the moment?

**Comment by schell** [comment]
This is possible, but it's not automatic. You would essentially have to do the code separation by hand. Either by using separate cargo binaries or by using special configuration.

**Comment by d4h0** [comment]
Okay, thank you, I will try this then. I'll probably experiment with creating micro apps with mogwai (mostly small widgets) which will be included in pages as needed.

**Comment by schell** [comment]
That sounds like a good strategy.
