### ISSUE TITLE
participate in realworld showcase 

### ISSUE THREAD

**Issue by kindlychung** [schell/mogwai#50]
https://github.com/gothinkster/realworld is a collection of frontend demos showing how to do things in a "real world" web app. 

Seed.rs has participated in it, FYI. Would be nice to see mogwai there, too!

**Comment by schell** [comment]
Thanks for the nudge @kindlychung :) 

I've already started a realworld demo at [mogwai-realworld](https://github.com/schell/mogwai-realworld) ;)

If I remember correctly it has register, login and settings components finished. For some value of "finished".

Maybe it would be better to host it as an example in _this_ repo? @kindlychung what do you think?

**Comment by kindlychung** [comment]
Yeah, either as an example or a link in the Readme, both are fine for me. Kudos for your nice work!
