### ISSUE TITLE
Should "async" family of functions in txrx only exist for wasm32 arch?

### ISSUE THREAD

**Issue by bryanjswift** [schell/mogwai#52]
`txrx.rs` uses `use wasm_bindgen_futures::spawn_local;` which I think needs to not be included if `target_arch` is something other than "wasm32"

**Comment by schell** [comment]
That's probably a good callout. I haven't run into trouble yet but I don't think I've tried using `send_async` server-side.

**Comment by bryanjswift** [comment]
I think this is closed with the merge of #53
