### ISSUE TITLE
Add support channel for Q/A

### ISSUE THREAD

**Issue by charleschege** [schell/mogwai#54]
Create a support channel where beginners can get help, like a discord or mattermost channel

**Comment by schell** [comment]
This is interesting. I understand the need for better beginner material but I'm not sure that I can realistically commit to maintaining a realtime channel. I'm working on a series of small tutorials in the [cookbook](https://github.com/schell/mogwai/tree/master/cookbook), which is a start. 

I'll keep this open as I do think it's a good idea in the long run.

...

Whelp, I've been meaning to play around with matrix so I created a matrix channel: https://matrix.to/#/!iABugogSTxJNzlrcMW:matrix.org?via=matrix.org

We'll see how it goes.

**Comment by charleschege** [comment]
The matrix channel is enough. Thanks for looking into this
