### ISSUE TITLE
Cookbook link not working and infinite scrolling.

### ISSUE THREAD

**Issue by blmhemu** [schell/mogwai#70]
![image](https://user-images.githubusercontent.com/19410501/99177866-7e41f800-2733-11eb-8c79-82fa81979b1d.png)
Also, a small question :
Is infinite scrolling (like say Netflix, Amazon Prime) possible ?

**Comment by schell** [comment]
Thanks for the report - I recently added cloudfront caching in front of the s3 static site and it looks like root links don't forward to `index.html`.

Yes - infinite scrolling is possible - I don't have any examples but the same techniques used with other libraries/frameworks should work just the same with mogwai.
