### ISSUE TITLE
SPA route example

### ISSUE THREAD

**Issue by schell** [schell/mogwai#71]
@charleschege pointed out (in the support channel) that there's no simple routing example. We should pull out the routing from [mogwai-realworld](https://github.com/schell/mogwai-realworld) and put it into an example and/or the cookbook.

**Comment by charleschege** [comment]
If there would also be a way to auto test the examples to prevent incompatibilities with newer versions of mogwai.

**Comment by charleschege** [comment]
I ran into some issues when with Unsupported modules with the routing example

**Comment by schell** [comment]
Hrm, @charleschege - each example should be getting built and tested w/ CICD. Can you explain in more detail the error you saw? Which routing example was this?

**Comment by schell** [comment]
Also, I just posted this new example to the cookbook https://zyghost.com/guides/mogwai-cookbook/routing.html. You can find the code in the examples folder https://github.com/schell/mogwai/tree/master/examples/spa-routing.

**Comment by charleschege** [comment]
> Hrm, @charleschege - each example should be getting built and tested w/ CICD. Can you explain in more detail the error you saw? Which routing example was this?

This line does not compile 
https://github.com/schell/mogwai/blob/d1e83675f6cd6ae3cad8894d9b146fe21db96272/examples/multipage/src/lib.rs#L50
`mogwai_hydrator` module was not found. I am wondering whether it's a feature I need to enable or it has been deprecated?

**Comment by schell** [comment]
`mogwai_hydrator` is a crate in the `crates/` folder of this repo. I'll look into this and see if I can recreate it. What command are you using to build? From which directory?

**Comment by charleschege** [comment]
I was using wasm-pack. But the new examples have solved this issue

**Comment by charleschege** [comment]
The example provided causes a panic at https://github.com/schell/mogwai/blob/eae58f237dd32a49b94c78068ec89538d8eca414/examples/spa-routing/src/lib.rs#L266 as it can't find an `id` in the document. I solved this by adding a html tag with an `id` of `app` just before the body https://github.com/schell/mogwai/blob/eae58f237dd32a49b94c78068ec89538d8eca414/examples/spa-routing/index.html#L8
For example:
```html
<body>
    <div id="app"></div>
      <script type="module">
       ...
     </script>
</body> 
```
This should be added to prevent panics. I ran the example using `wasm-pack build --dev --target web`
