### ISSUE TITLE
Add Patch::Trim

### ISSUE THREAD

**Issue by schell** [schell/mogwai#72]
To trim the children of a node at run time.

**Comment by bryanjswift** [comment]
I don't think I have a good understanding of what `Patch::Trim` should do. Would this be removing child nodes that are empty?

**Comment by schell** [comment]
This would "keep" the first `n` children and remove the rest. Conversely there would also be a variant that denote "dropping" the first `n` children and keeping the rest.

I've already added these as `Patch::Keep` and `Patch::Drop` in v0.3.6, so I'll close this now.
