### ISSUE TITLE
Render complex svg easily 

### ISSUE THREAD

**Issue by charleschege** [schell/mogwai#75]
The svg example works due to its simplicity, but It's not clear how to render complex svg elements for example https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=78d7338cb9955c8faabae0aba23586d7

How would you use builder macro to render that?

**Comment by charleschege** [comment]
Things like icons and svg logos have complex svg markup, an easy way to render this is necessary

**Comment by schell** [comment]
I think the issue was that each node needs to have the `xmlns` attribute.
