### ISSUE TITLE
Add to cookbook how to listen to multiple events for the same element 

### ISSUE THREAD

**Issue by charleschege** [schell/mogwai#79]
How do I listen for two or more events on the same html element. For example, listening to `focusin` and `focusout` events on the same element 

```rust
#[wasm_bindgen]
pub fn main(parent_id: Option<String>) -> Result<(), JsValue> {
    panic::set_hook(Box::new(console_error_panic_hook::hook));
    console_log::init_with_level(Level::Trace).unwrap();

    let (block_patch_tx, block_patch_rx) = txrx::<Patch<ViewBuilder<HtmlElement>>>();
    let (focused_tx, focused_rx) = (block_patch_tx.clone(), block_patch_rx.clone());

    let view = View::from(builder! {
        <section class="frow direction-column">
            <div id="editor" class="frow direction-column width-100" data-block-editor="browser-wasm">
                <div contenteditable="true" class="frow direction-column width-100 row-center" data-block="heading1"

                     //how do I listen to multiple events here
on:focusin=block_tx.clone().contra_map(move |_: &Event| {
                        block_patch_tx.send(&Patch::<ViewBuilder<HtmlElement>>::Insert{index: 0, value: textops()})
                    })
                    on:focusout=block_tx.clone().contra_map(move |_: &Event| {
                        block_patch_tx.send(&Patch::<ViewBuilder<HtmlElement>>::Remove{index: 0})
                    })
                patch:children=block_patch_rx>
                    <div>"This is heading 1"</div>
                </div>
        </section>
    });

    if let Some(id) = parent_id {
        let parent = utils::document().get_element_by_id(&id).unwrap();

        view.run_in_container(&parent)
    } else {
        view.run()
    }
}

fn textops() -> ViewBuilder<HtmlElement>{

} 
```

**Comment by schell** [comment]
This should work pretty much as you have it written, though you'll probably have to clone `block_patch_tx` to move it into each respective closure.

What is the error you are receiving?

**Comment by charleschege** [comment]
I have managed to solve the `move` issue that forced me to move the ownership of the transmitter to the closure.

**Comment by charleschege** [comment]
![Peek 2021-03-09 18-46](https://user-images.githubusercontent.com/33346042/110567852-33754180-8163-11eb-8612-375ada8b2f9d.gif)
This is the effect I am trying to achieve.

**Comment by charleschege** [comment]
I am trying to listen for the event on all divs in a page but add or remove sections based on when an element has focus or not. How do I listen globally for focusin event on a `div` with `data-block` attribute and add a `textops()` block and then remove the `textops()` code from that same element when it loses focus through `focusout` browser event but still be able to add `textops()` code to the new element that has focus

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=783ef3bfbcf9d574a990adef192773fa

**Comment by schell** [comment]
I've created an example of this in the `examples/` folder, hopefully that solves your problem, feel free to re-open otherwise :)
