### ISSUE TITLE
[IDEA] TUI and other View types

### ISSUE THREAD

**Issue by OvermindDL1** [schell/mogwai#81]
`mogwai` would be very well suited for updating a terminal user interface as it would make it simple to only update the part of the screen that needs it.  Currently the `Component` trait is geared towards HTML only, so would it be an interesting idea to split it up into a `Component` and something like a WebView trait, that way some other view traits could be made, like perhaps a CursiveView for one such TUI (or something lower level would even fit better) for something else, and perhaps others could be made for other purposes in the future as well.  I could imagine `Gizmo` getting a type argument to determine what view it's pulling from, and as such how to wire things up.

**Comment by d4h0** [comment]
This would be amazing :)

Just yesterday I thought about how great a native, reactive Rust GUI framework probably would be – and this proposal would make this possible, I believe.

I'd love to be able to use a single UI framework to create WASM apps, TUI tools, and applications with a native UI (possible with mogwai-powered WebViews for stuff that's easier with web technologies).

A TUI backend seems like a great way to prototype such a flexible rendering architecture.

**Comment by schell** [comment]
This sounds pretty cool. I'll take a look at what that might take. Thank you!

**Comment by schell** [comment]
In the next release `View` and `ViewBuilder`'s type variable refer to the domain mogwai is being used in, instead of the type of the widget. 

This allowed me to write a majority of the functionality on generic `ViewBuilder<T>`, which means we can fill in the `T` with some domain specific type later. 

For the web and server-side rendering the domain specific type is `Dom`, which represents a DOM node. I will leave the implementation of other domain specific types up to users.

**Comment by d4h0** [comment]
This is amazing, thank you, @schell.

Will there be a tutorial or example or something like that?

I guess, `mogwai` itself would be an example, but maybe not the easiest to grasp, I think.

I'm going to start to build a TUI app soon, so I'm pretty interested in playing with this :)

**Comment by schell** [comment]
Yes I think I'll try writing a cookbook entry for it. 

The main thing to do is to write an implementation of `TryFrom<DecomposedViewBuilder<V>> for View<V>` where `V` is your domain specific node type.

`DecomposedViewBuilder` is basically a `ViewBuilder` with all of the values *right now* separated from all of the streaming future values (and also any post-build operations). 

You can see how it's done for `Dom` [here](https://github.com/schell/mogwai/blob/8df9673a5bdfedb9f5ddd3aaea2666fc8a636c38/crates/mogwai/src/builder.rs#L545-L717).
