### ISSUE TITLE
Fragment Syntax or ViewBuilder<Vec<HtmlElement>>

### ISSUE THREAD

**Issue by cryptoquick** [schell/mogwai#82]
I'm aware not all JSX idioms don't always map to TEA projects, but I was wondering if it might be nice to be able to do either of these:

**JSX Fragment Syntax**

```rust
fn component() -> ViewBuilder<HtmlElement> {
    builder! {
        <>
            <div></div>
            <div></div>
        </>
    }
}

fn parent_component() -> ViewBuilder<HtmlElement> {
    builder! {
        <div id="wrap">
            {component()}
        </div>
    }
}
```

`ViewBuilder<Vec<HtmlElement>>`

```rust
fn component() -> ViewBuilder<Vec<HtmlElement>> {
    builder! {
        <div></div>
        <div></div>
    }
}

fn parent_component() -> ViewBuilder<HtmlElement> {
    builder! {
        <div id="wrap">
            {component()}
        </div>
    }
}
```

Right now I have to do it this way, which is perfectly fine, I suppose:

```rust
fn component() -> ViewBuilder<HtmlElement> {
    builder! {
        <div id="mydiv">
            <div></div>
            <div></div>
        </div>
    }
}

fn parent_component() -> ViewBuilder<HtmlElement> {
    builder! {
        <div id="wrap">{component()}</div>
    }
}
```

Just a nice-to-have.

**Comment by schell** [comment]
I'm investigating this now. The main issue is `SsrNode` needs to be expanded to support fragments.

**Comment by schell** [comment]
:rubber_ducking:

Another complication is that after a `DocumentFragment` is added to the DOM, its child nodes are drained and given to the parent the fragment was added to. This has the ramification that any streams with side-effects affecting the fragment are either on the wrong target (they should be on the new parent) or are mutating the out-of-band fragment.

**Comment by schell** [comment]
Turns out I was thinking too hard about this. Instead of `ViewBuilder<Vec<Dom>>` we can simply allow appending iterators of `ViewBuilder` or `Into<ViewBuilder>`: 

```rust 
        let vs: Vec<ViewBuilder<Dom>> = builder! {
            <div>"hello"</div>
            <div>"hola"</div>
            <div>"kia ora"</div>
        };

        let s: ViewBuilder<Dom> = builder! {
            <section>{vs}</section>
        };
        let view: View<Dom> = s.try_into().unwrap();
        assert_eq!(
            String::from(view).as_str(),
            "<section><div>hello</div> <div>hola</div> <div>kia ora</div></section>"
        );
        ```

This will be available in the 0.5 release.

**Comment by cryptoquick** [comment]
Love it! Looking forward to it.

**Comment by cryptoquick** [comment]
also, Rust rly do be like that sometimes uwu
