### ISSUE TITLE
is this still maintained?

### ISSUE THREAD

**Issue by yatesco** [schell/mogwai#83]
Hi there - this looks really interesting, but the lack of any commits since May concerns me slightly - is this still actively used and maintained? Is this simply "complete"?

Thanks!

**Comment by bryanjswift** [comment]
Commits have been happening in the [`gremlin`](https://github.com/schell/mogwai/tree/gremlin) branch. Based on conversations in the [matrix room](https://matrix.to/#/!iABugogSTxJNzlrcMW:matrix.org?via=matrix.org) @schell is working towards the next release with some significant changes.

**Comment by yatesco** [comment]
Yes - I was a numpty and I thought the date stamp was for all branches, not just the currently selected branch - doh!

**Comment by schell** [comment]
Yes @yatesco, I've been working in the `gremlin` branch. The `0.5` release will have some hefty changes, though the idea remains the same (I'm removing my own channel impl in favor of `futures`' `Stream` and `Sink`). 

Thanks @bryanjswift :)
