### ISSUE TITLE
Creating a View/ViewBuilder from a Vec

### ISSUE THREAD

**Issue by paulalesius** [schell/mogwai#85]
Hi

Is it possible to create a list of elements?

```rust
impl From<Vec<HtmlElement>> for ViewBuilder<HtmlElement> {
    fn from(vec: Vec<HtmlElement>) -> Self {
        builder! {
            // How do you construct a ViewBuilder or View from a Vec of elements?
        }
    }
}
```

I've found no example, and none of the code I've looked at is using a Vec of items. I'd want to pre-create a list of items so that they are displayed at once, instead of sending them one by one.

Thank you for a great framework!

**Comment by bryanjswift** [comment]
I think this is related to https://github.com/schell/mogwai/issues/82

**Comment by paulalesius** [comment]
Thank you for the quick reply! I just read that but did not understand what it meant by "fragment", sorry. Closing! 👍

**Comment by schell** [comment]
Yes, the next release will allow adding a vector of `ViewBuilder` like so: 
```rust
        let vs: Vec<ViewBuilder<Dom>> = builder! {
            <div>"hello"</div>
            <div>"hola"</div>
            <div>"kia ora"</div>
        };

        let s: ViewBuilder<Dom> = builder! {
            <section>{vs}</section>
        };
        let view: View<Dom> = s.try_into().unwrap();
        assert_eq!(
            String::from(view).as_str(),
            "<section><div>hello</div> <div>hola</div> <div>kia ora</div></section>"
        );
```
